global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'balios-example'
    replica: '0'

scrape_configs:
  - job_name: 'balios'
    static_configs:
      - targets: ['app:2112']
        labels:
          instance: 'balios-cache'
          env: 'example'
