name: PR Quick Check

on:
  pull_request:
    branches: [ main ]

env:
  CGO_ENABLED: 1

jobs:
  quick-test:
    name: Quick Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: true

    - name: Quick Quality Check
      run: |
        # Format check
        test -z "$(gofmt -l .)"
        
        # Vet
        go vet ./...
        
        # Basic test
        go test -short ./...

    - name: Install Security Tools
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Security Scan
      run: |
        # Run gosec; allow SSA analyzer crashes if no security issues found
        if ! gosec --exclude=G104,G306,G301 ./...; then
          # Check if failure was due to SSA analyzer crash (exit 1) with 0 issues
          echo "Gosec exited with error. This is acceptable if no security issues were found."
          # Re-run with verbose output to verify
          gosec --exclude=G104,G306,G301 ./... 2>&1 | tee gosec.log
          if grep -q "Issues : 0" gosec.log; then
            echo "✓ No security issues found (SSA analyzer crash ignored)"
            exit 0
          else
            echo "✗ Security issues detected!"
            exit 1
          fi
        fi
