name: PR Quick Check

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  CGO_ENABLED: 1

jobs:
  quick-test:
    name: Quick Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: 'stable'
        cache: true

    - name: Quick Quality Check
      run: |
        # Format check
        test -z "$(gofmt -l .)"
        
        # Vet
        go vet ./...
        
        # Basic test
        go test -short ./...

    - name: Install Security Tools
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Security Scan
      run: gosec --exclude=G104,G306,G301 ./...
